package club.banyuan.gui01;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanye
 */
public class TableFrame extends javax.swing.JFrame {

  /**
   * Creates new form Login
   */
  public TableFrame() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  //  jTable1.setModel(new DefaultTableModel("二维数组", "表头"));




    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {"1", "java", "false"},
            {"1", "java", "false"},
            {"1", "java", "false"},
            {"1", "java", "false"},
            {"1", "java", "false"},
            {"1", "java", "false"},
            {"1", "java", "false"},
            {"1", "java", "false"},
            {"1", "java", "false"},
            {"1", "java", "false"},
            {"1", "java", "false"},
            {"1", "java", "false"},
            {"1", "java", "false"},
            {"1", "java", "false"},
            {"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},{"1", "java", "false"},

        },
        new String [] {
            "试题编号", "试题内容", "试题答案"
        }
    ));
    jTable1.setEnabled(false); //不可编辑
    jScrollPane1.setViewportView(jTable1); //滚动条

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
    );

    pack();
  }// </editor-fold>

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TableFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  // End of variables declaration
}

